### ISSUE TITLE
Notebook tutorial as in VlaPy?

### ISSUE THREAD

**Issue by matteoguarrera** [ergodicio/adept#44]
Hi! Thanks for the amazing work. I was wondering if you have some tutorial ready as in VlaPy!
Best,
Matteo

**Comment by joglekara** [comment]
No I don't but I should, they will be very helpful because the documentation is incomplete to say the least. 

I think I will make a new repo with some example notebooks. TY for the suggestion.

**Comment by joglekara** [comment]
here you go! https://github.com/ergodicio/adept-notebooks
